# Generated by Django 5.1.2 on 2024-10-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userid',
        ),
    ]
