# Generated by Django 5.1.2 on 2024-10-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_fname_profile_lname_profile_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.IntegerField(default=1),
        ),
    ]
