# Generated by Django 5.1.2 on 2024-10-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileimg',
        ),
        migrations.AddField(
            model_name='profile',
            name='profimg',
            field=models.ImageField(default='blank.png', upload_to='profimg/'),
        ),
    ]
