# Generated by Django 5.1.2 on 2024-10-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='users',
        ),
    ]
